### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by tuxalex** [julienmalik/shaarli_ynh#7]
Hi,
I have an installation error. 
I  have removed in the install script | python ../conf/user_list.py because "../conf/user_list.py" doesn't exist.
And after that, the installation work find.

**Comment by julienmalik** [comment]
I don't understand.
The file does exist : https://github.com/julienmalik/shaarli_ynh/blob/master/conf/user_list.py

**Comment by lapineige** [comment]
Maybe @tuxalex is refering to that error when installing:
>++ python ../conf/user_list.py
Warning: Traceback (most recent call last):
Warning:   File "../conf/user_list.py", line 3, in <module>
Warning:     print "{0}".format("\n".join(i["username"] for i in userlist))
Warning:   File "../conf/user_list.py", line 3, in <genexpr>
Warning:     print "{0}".format("\n".join(i["username"] for i in userlist))
Warning: TypeError: string indices must be integers
>++ sudo php ../conf/init_config_user.php
Warning: PHP Notice:  Undefined index: login in /var/cache/yunohost/from_file/shaarli_ynh-master/conf/init_config_user.php on line 39
Warning: PHP Notice:  Undefined index: password in /var/cache/yunohost/from_file/shaarli_ynh-master/conf/init_config_user.php on line 40
Warning: PHP Notice:  Undefined index: level in /var/cache/yunohost/from_file/shaarli_ynh-master/conf/init_config_user.php on line 41
Warning: PHP Notice:  Undefined index: email in /var/cache/yunohost/from_file/shaarli_ynh-master/conf/init_config_user.php on line 42

I have this error when trying to install, and after that I can't add a link (there's no way to do it using the website UI, I need to change the URL, and it ask for a login)

**Comment by lapineige** [comment]
This PR solves the issue I mentioned. (tested on yunohost 2.4)

**Comment by lapineige** [comment]
@tuxalex PR merged now, could you test it again ? :)
